name: build-v2

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
      - '**.yml'
  workflow_dispatch:

env:
  NRF52: 'adafruit:nrf52:pca10056'
  # arduino-cli board details -b esp32:esp32:esp32
  ESP32: 'esp32:esp32:esp32:PartitionScheme=min_spiffs,CPUFreq=240,PSRAM=enabled,FlashFreq=80,FlashMode=dio,FlashSize=4M,DebugLevel=none'
  # arduino-cli board details -b esp32:esp32:esp32s3
  ESP32S3: 'esp32:esp32:esp32s3:PartitionScheme=default_8MB,CPUFreq=240,PSRAM=enabled,FlashMode=qio,FlashSize=8M,DebugLevel=none,CDCOnBoot=cdc,USBMode=default'

jobs:
  build-v2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uf2, Arduino and Python
        shell: bash
        run: |
          git clone https://github.com/microsoft/uf2 ~/uf2

          mkdir -p ~/.local/bin
          curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | BINDIR=~/.local/bin sh

          mkdir $HOME/Arduino
          ln -s $GITHUB_WORKSPACE/software/firmware/source/libraries $HOME/Arduino/libraries

          sudo apt-get update --fix-missing
          sudo apt-get install python3-full

          pip3 install adafruit-nrfutil --user
          
      - name: Install boards
        shell: bash
        run: |
            arduino-cli config init
            arduino-cli config add board_manager.additional_urls https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json
            arduino-cli config add board_manager.additional_urls https://adafruit.github.io/arduino-board-index/package_adafruit_index.json
            arduino-cli core update-index
            arduino-cli core install esp32:esp32@2.0.9
            arduino-cli core install adafruit:nrf52

            if [[ ! -f ~/.local/bin/adafruit-nrfutil ]]; then
              ln -s /bin/true ~/.local/bin/adafruit-nrfutil
            fi

      - name: Build SoftRF
        run: |
          echo "#define CURRENT_DATE \"$(date +"24%m%d")\"" > $GITHUB_WORKSPACE/software/firmware/source/SoftRF/current_date.h

          cd $GITHUB_WORKSPACE
          arduino-cli compile -e -b "$NRF52" $GITHUB_WORKSPACE/software/firmware/source/SoftRF
          cd "$GITHUB_WORKSPACE/software/firmware/source/SoftRF/build/adafruit.nrf52.pca10056"
          ~/uf2/utils/uf2conv.py SoftRF.ino.hex -c -f 0xADA52840 -o SoftRF.ino.uf2
          rm -f *.elf
          rm -f *.map
          rm -f *.hex
          rm -f *.zip

          cd $GITHUB_WORKSPACE
          arduino-cli compile -e -b "$ESP32" $GITHUB_WORKSPACE/software/firmware/source/SoftRF
          cd "$GITHUB_WORKSPACE/software/firmware/source/SoftRF/build/esp32.esp32.esp32"
          cp -f $GITHUB_WORKSPACE/software/firmware/source/SoftRF/boot_app0.bin .
          rm -f *.elf
          rm -f *.map

          cd $GITHUB_WORKSPACE
          cp -f $GITHUB_WORKSPACE/software/firmware/source/SoftRF/partitions-8MB-SPIFFS.txt /home/runner/.arduino15/packages/esp32/hardware/esp32/2.0.9/tools/partitions/default_8MB.csv
          arduino-cli compile -e -b "$ESP32S3" $GITHUB_WORKSPACE/software/firmware/source/SoftRF
          cd "$GITHUB_WORKSPACE/software/firmware/source/SoftRF/build/esp32.esp32.esp32s3"
          ~/uf2/utils/uf2conv.py SoftRF.ino.bin -b 0x00 -c -f 0xc47e5767 -o SoftRF.ino.uf2
          rm -f *.elf
          rm -f *.map
          rm -f *.bin

      - uses: actions/upload-artifact@v4
        with:
          name: SoftRF
          path: |
            software/firmware/source/SoftRF/build/
          if-no-files-found: error
